<testExecutions version="1">
<file path="Test\app.test.js">
<testCase name="GET /guests: should get all Guests record" duration="225"/>
<testCase name="GET /guests: should get a single Guest record" duration="0">
<failure message="expected [] to be an object"><![CDATA[AssertionError: expected [] to be an object
    at a (Test/app.test.js:28:40)
    at Test.Request.callback (node_modules\superagent\lib\node\index.js:716:12)
    at D:\projects\guestbook-full\guestbook-backend\node_modules\superagent\lib\node\index.js:916:18
    at IncomingMessage.<anonymous> (node_modules\superagent\lib\node\parsers\json.js:19:7)
    at endReadableNT (_stream_readable.js:1130:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)]]></failure>
</testCase>
<testCase name="GET /guests: should not get a single Guest record" duration="0">
<failure message="expected { Object (_events, _eventsCount, ...) } to have status code 404 but got 200"><![CDATA[AssertionError: expected { Object (_events, _eventsCount, ...) } to have status code 404 but got 200
    at status (Test/app.test.js:39:37)
    at Test.Request.callback (node_modules\superagent\lib\node\index.js:716:12)
    at D:\projects\guestbook-full\guestbook-backend\node_modules\superagent\lib\node\index.js:916:18
    at IncomingMessage.<anonymous> (node_modules\superagent\lib\node\parsers\json.js:19:7)
    at endReadableNT (_stream_readable.js:1130:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)]]></failure>
</testCase>
</file>
</testExecutions>
